FROM python:3.9-slim
RUN pip install --upgrade pip

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy the current directory contents into the container at /code
RUN python -m django --version
